remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [EQUIP: Error Correction for Quantum Information Processing]
# description: [A short description of your site's purpose]